apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fleet
  labels:
    app: nginx-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-fleet
  template:
    metadata:
      labels:
        app: nginx-fleet
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fleet
spec:
  type: NodePort
  selector:
    app: nginx-fleet
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000  # 任意のNodePort（30000-32767範囲内）
